name: Build and Push OCI Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  prepare:
    name: Determine Image Tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.determine-tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history to check branch ancestry

      - name: Determine Docker tag based on Git ref
        id: determine-tag
        run: |
          # Since this workflow only triggers on tags matching 'v*.*.*' we know we're always dealing with a version tag, we know we're always dealing with a version tag
          
          TAG_BRANCHES=$(git branch -r --contains ${{ github.sha }} | grep -E '(origin/main|origin/master)' || true)

          if [[ -n "$TAG_BRANCHES" ]]; then
            TAG_NAME="${{ github.ref_name }}"
            TAG_NAME="${TAG_NAME#v}"  # Remove 'v' prefix
            echo "Processing tag on main branch: ${{ github.ref_name }} -> ${TAG_NAME}"
          else
            echo "Error: Tag ${{ github.ref_name }} is not on main branch"
            echo "Tags must be created on main branch to generate X.Y.Z image tags"
            exit 1
          fi
          
          echo "tag=${TAG_NAME}" >> "$GITHUB_OUTPUT"
          echo "Determined image tag: ${TAG_NAME}"