name: Build and Push OCI Image

on:
  workflow_run:
    workflows: ["Conventional Commit Check PR Title"]
    types:
      - completed
    branches:
      - main
      - 'feature/*'
      - 'bugfix/*'
    tags:
      - 'v*.*.*' # Triggers on version tags like v1.0.0

jobs:
  prepare:
    name: Determine Image Tag
    runs-on: ubuntu-latest
    # Only run if the triggering workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      tag: ${{ steps.determine-tag.outputs.tag }}
    steps:
      - name: Determine Docker tag based on Git ref
        id: determine-tag
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)

          if [[ "${{ github.ref_type }}" == "tag" ]] && [[ "${{ github.ref_name }}" == "main" || "${{ github.event.base_ref }}" == "refs/heads/main" ]]; then
            TAG_NAME="${{ github.ref_name }}"
            TAG_NAME="${TAG_NAME#v}"  # Remove 'v' prefix using bash parameter expansion
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            TAG_NAME="dev-${SHORT_SHA}"
          elif [[ "${{ github.ref_name }}" =~ ^feature/ ]] || [[ "${{ github.ref_name }}" =~ ^bugfix/ ]]; then
            TAG_NAME="feature-${SHORT_SHA}"
          else
            echo "Error: Unsupported branch or ref type: ${{ github.ref_name }}"
            echo "Supported patterns: main, feature/*, bugfix/*, or tags"
            exit 1
          fi
          
          echo "tag=${TAG_NAME}" >> "$GITHUB_OUTPUT"
          echo "Determined image tag: ${TAG_NAME}"

  build-and-publish:
    name: Build and Publish to Registry
    needs: prepare
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/docker-build.yml@main
    with:
      registry: docker-regis.iex.ec
      image-name: docker-regis.iex.ec/tee-worker-pre-compute-rust
      image-tag: ${{ needs.prepare.outputs.tag }}
      push: true
    secrets:
      username: ${{ secrets.DOCKER_REGIS_USERNAME }}
      password: ${{ secrets.DOCKER_REGIS_PASSWORD }}