name: Build and Push OCI Image

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'bugfix/**'
    tags:
      - 'v*.*.*'

jobs:
  prepare:
    name: Determine Image Tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.determine-tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Determine Docker tag based on Git ref
        id: determine-tag
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)

          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            TAG_BRANCHES=$(git branch -r --contains ${{ github.sha }} | grep -E '(origin/main|origin/master)' || true)
  
            if [[ -n "$TAG_BRANCHES" ]]; then
              TAG_NAME="${{ github.ref_name }}"
              TAG_NAME="${TAG_NAME#v}"
              echo "Processing tag on main branch: ${{ github.ref_name }} -> ${TAG_NAME}"
            else
              echo "Error: Tag ${{ github.ref_name }} is not on main branch"
              echo "Tags must be created on main branch to generate X.Y.Z image tags"
              exit 1
            fi
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            TAG_NAME="dev-${SHORT_SHA}"
            echo "Processing main branch push -> ${TAG_NAME}"
          elif [[ "${{ github.ref_name }}" =~ ^feature/ ]] || [[ "${{ github.ref_name }}" =~ ^bugfix/ ]]; then
            TAG_NAME="feature-${SHORT_SHA}"
            echo "Processing feature/bugfix branch: ${{ github.ref_name }} -> ${TAG_NAME}"
          else
            echo "Error: Unsupported branch or ref type: ${{ github.ref_name }}"
            echo "Supported patterns: main, feature/*, bugfix/*, or tags"
            exit 1
          fi
          
          echo "tag=${TAG_NAME}" >> "$GITHUB_OUTPUT"
          echo "Determined image tag: ${TAG_NAME}"
